definitions:
  main.Quest:
    properties:
      cost:
        type: integer
      id:
        type: integer
      is_reusable:
        type: boolean
      name:
        type: string
      reusable_limit:
        type: integer
    type: object
  main.User:
    properties:
      balance:
        type: integer
      id:
        type: integer
      name:
        type: string
    type: object
info:
  contact: {}
paths:
  /quest:
    post:
      consumes:
      - application/json
      description: Create a new quest with the given name, cost, and reusability options
      parameters:
      - description: Quest object
        in: body
        name: quest
        required: true
        schema:
          $ref: '#/definitions/main.Quest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/main.Quest'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Create a new quest
      tags:
      - quests
  /user:
    post:
      consumes:
      - application/json
      description: Create a new user with the given name and balance
      parameters:
      - description: User object
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/main.User'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/main.User'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Create a new user
      tags:
      - users
  /user/{id}:
    get:
      consumes:
      - application/json
      description: Get information about a user with the given ID
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.User'
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get user information
      tags:
      - users
swagger: "2.0"
